name: ZoneFall
version: '1.0-SNAPSHOT'
main: dev.recro.zoneFall.ZoneFall
api-version: '1.21'
commands:
  debug:
    description: help command
    usage: /<command>
  worth:
    description: worth command
    usage: /<command>
  sell:
    description: sell command
    usage: /<command>
  stats:
    description: stats command
    usage: /<command>
  balance:
    description: balance command
    usage: /<command>
    aliases: [bal]
  pay:
    description: balance command
    usage: /<command>
    aliases: [bal]